### ISSUE TITLE
train-name参数应该改为train-names

### ISSUE THREAD

**Issue by cdlwhm1217096231** [hack12306/12306-booking#7]
大佬,你好!你的用法使用介绍时,下面的train-name参数应该改为train-names,否则会提示参数错误
123060-booking --train-date 2020-01-01 --train-name K571 --seat-types 硬卧 --from-station 北京 --to-station 麻城 --pay-channel 微信 --passengers 任正非,王石，

**Comment by hotbaby** [comment]
更新了😆 @cdlwhm1217096231
